export enum RoleEnum {
  REGISTRATION_STAFF = "NHAN_VIEN_BAN_HO_SO",
  AUCTIONEER = "DAU_GIA_VIEN",
  SECRETARY = "THU_KY",
  SPECIALIST = "CHUYEN_VIEN",
  ARCHIVIST = "NHAN_VIEN_LUU_TRU",
  ADMIN = "ADMIN",
}
